import { describe, it, expect } from 'vitest';
import {
  resolveSessionSecret,
  SESSION_SECRET_ENV,
  SESSION_SECRET_KEY,
  SHIPPED_SESSION_SECRET,
  PLACEHOLDER_SESSION_SECRETS
} from '../sessionSecret.js';

/**
 * #1194 — the session secret fell back to the literal shipped in
 * `config/app-default-config.json`, so an instance that set neither
 * `NGDPBASE_SESSION_SECRET` nor a config override signed every session with
 * a public string. Two live instances were doing so.
 *
 * Operator rule: the variable MUST be defined in `.env`; refuse to boot if it
 * is not. The check is on the variable, not the resolved config value, so the
 * key keeps the single env owner #1089 declared for it.
 */
describe('resolveSessionSecret', () => {
  it('returns the configured value', () => {
    expect(resolveSessionSecret({ [SESSION_SECRET_ENV]: 'a-real-secret' })).toBe('a-real-secret');
  });

  it('trims surrounding whitespace, which a .env line can carry', () => {
    expect(resolveSessionSecret({ [SESSION_SECRET_ENV]: '  a-real-secret \n' })).toBe('a-real-secret');
  });

  it('refuses when the variable is absent', () => {
    expect(() => resolveSessionSecret({})).toThrow(/is not set/);
  });

  it('refuses when the variable is blank', () => {
    expect(() => resolveSessionSecret({ [SESSION_SECRET_ENV]: '   ' })).toThrow(/is not set/);
  });

  it('refuses the literal shipped in app-default-config.json', () => {
    expect(() => resolveSessionSecret({ [SESSION_SECRET_ENV]: SHIPPED_SESSION_SECRET })).toThrow(/placeholder/);
  });

  it('refuses every documented example value', () => {
    for (const placeholder of PLACEHOLDER_SESSION_SECRETS) {
      expect(() => resolveSessionSecret({ [SESSION_SECRET_ENV]: placeholder }), placeholder).toThrow(/placeholder/);
    }
  });

  it('does not look at the config key — a config-file value cannot satisfy it', () => {
    // The check is deliberately blind to any other source. Passing the config
    // key's name as an env var is the closest thing to "set it somewhere else".
    expect(() => resolveSessionSecret({ [SESSION_SECRET_KEY]: 'a-real-secret' })).toThrow(/is not set/);
  });

  it('names the variable and the generator so the message is actionable, and never echoes the value', () => {
    let message = '';
    try {
      resolveSessionSecret({ [SESSION_SECRET_ENV]: SHIPPED_SESSION_SECRET });
    } catch (err) {
      message = (err as Error).message;
    }
    expect(message).toContain(SESSION_SECRET_ENV);
    expect(message).toContain('openssl rand');
    expect(message).toContain('#1194');
    expect(message).not.toContain(SHIPPED_SESSION_SECRET);
  });

  it('SABOTAGE: the shipped literal is the one in the config file', async () => {
    // If someone edits the shipped value without updating this constant, the
    // guard would accept the new public literal. Read the file, not a copy.
    const fs = await import('fs');
    const cfg = JSON.parse(fs.readFileSync('config/app-default-config.json', 'utf8')) as Record<string, unknown>;
    expect(cfg[SESSION_SECRET_KEY]).toBe(SHIPPED_SESSION_SECRET);
  });
});

import { ensureSessionSecret, type SessionSecretFs } from '../sessionSecret.js';

/** In-memory .env so the backfill is proven without touching a real data dir. */
function fakeFs(initial: Record<string, string> = {}): SessionSecretFs & { files: Record<string, string>; modes: Record<string, number> } {
  const files = { ...initial };
  const modes: Record<string, number> = {};
  return {
    files,
    modes,
    readFile: (p) => (p in files ? files[p] : null),
    appendFile: (p, line, mode) => {
      if (!(p in files)) modes[p] = mode;
      files[p] = (files[p] ?? '') + line;
    },
    randomSecret: () => 'GENERATED-SECRET'
  };
}

describe('ensureSessionSecret (#1194 backfill)', () => {
  const dir = '/data';
  const envPath = '/data/.env';

  it('uses the ambient value and writes nothing', () => {
    const fs = fakeFs();
    const r = ensureSessionSecret({ [SESSION_SECRET_ENV]: 'ambient' }, dir, fs);
    expect(r).toEqual({ secret: 'ambient', origin: { kind: 'env' } });
    expect(fs.files).toEqual({});
  });

  it('refuses an ambient placeholder rather than overwriting the operator\'s line', () => {
    const fs = fakeFs();
    expect(() => ensureSessionSecret({ [SESSION_SECRET_ENV]: 'change-me-in-production' }, dir, fs)).toThrow(/placeholder/);
    expect(fs.files).toEqual({});
  });

  it('generates, creates the instance .env 0600, and returns the generated origin', () => {
    const fs = fakeFs();
    const r = ensureSessionSecret({}, dir, fs);
    expect(r.secret).toBe('GENERATED-SECRET');
    expect(r.origin).toEqual({ kind: 'generated', path: envPath });
    expect(fs.files[envPath]).toMatch(/^# Generated by ngdpbase[^\n]*\nNGDPBASE_SESSION_SECRET=GENERATED-SECRET\n$/);
    expect(fs.modes[envPath]).toBe(0o600);
  });

  it('appends to an existing .env on its own line, even when the file lacks a trailing newline', () => {
    const fs = fakeFs({ [envPath]: 'PORT=3000' });
    ensureSessionSecret({}, dir, fs);
    expect(fs.files[envPath]).toBe(
      'PORT=3000\n# Generated by ngdpbase on first boot (#1194). Rotating it signs everyone out.\nNGDPBASE_SESSION_SECRET=GENERATED-SECRET\n'
    );
  });

  it('tolerates a trailing slash on the data dir', () => {
    const fs = fakeFs();
    expect(ensureSessionSecret({}, '/data/', fs).origin).toEqual({ kind: 'generated', path: envPath });
  });

  it('prefers a value already in the instance .env when the environment carries it BLANK', () => {
    // compose `${VAR:-}` or `-e VAR=` — dotenv refuses to override an existing
    // key, so without this branch every boot would generate again.
    const fs = fakeFs({ [envPath]: 'NGDPBASE_SESSION_SECRET="from-file"\n' });
    const r = ensureSessionSecret({ [SESSION_SECRET_ENV]: '' }, dir, fs);
    expect(r).toEqual({ secret: 'from-file', origin: { kind: 'instance-env-file', path: envPath } });
    expect(fs.files[envPath]).toBe('NGDPBASE_SESSION_SECRET="from-file"\n');
  });

  it('reads the LAST occurrence and strips an inline comment, like dotenv', () => {
    const fs = fakeFs({ [envPath]: 'NGDPBASE_SESSION_SECRET=old\nexport NGDPBASE_SESSION_SECRET=new # rotated\n' });
    expect(ensureSessionSecret({}, dir, fs).secret).toBe('new');
  });

  it('refuses a placeholder found in the instance .env', () => {
    const fs = fakeFs({ [envPath]: `NGDPBASE_SESSION_SECRET=${SHIPPED_SESSION_SECRET}\n` });
    expect(() => ensureSessionSecret({}, dir, fs)).toThrow(/placeholder/);
  });

  it('refuses when the file cannot be written, naming the path and the generator', () => {
    const fs = fakeFs();
    fs.appendFile = () => { throw new Error('EROFS: read-only file system'); };
    let message = '';
    try {
      ensureSessionSecret({}, dir, fs);
    } catch (err) {
      message = (err as Error).message;
    }
    expect(message).toContain(envPath);
    expect(message).toContain('EROFS');
    expect(message).toContain('openssl rand');
    expect(message).not.toContain('GENERATED-SECRET');
  });

  it('SABOTAGE: a fallback that returned the shipped literal would be caught', () => {
    const fs = fakeFs();
    fs.randomSecret = () => SHIPPED_SESSION_SECRET;
    // Generation trusts its RNG; the check that matters is that the NEXT boot
    // reading that line refuses it, so a bad generator cannot persist.
    ensureSessionSecret({}, dir, fs);
    expect(() => ensureSessionSecret({}, dir, fs)).toThrow(/placeholder/);
  });
});
