#!/usr/bin/env tsx
/**
 * Regenerate the audit documentation from configuration (#1207).
 *
 * Two regions are generated, between marker pairs, and everything outside
 * the markers stays hand-written:
 *
 *   docs/managers/AuditManager.md   <!-- AUTO:audit-events BEGIN --> … END
 *     the event table: every entry of `ngdpbase.audit.events`, its tier,
 *     and whether it is recorded
 *
 *   docs/audit-posture.md           <!-- AUTO:audit-coverage BEGIN --> … END
 *     what the coverage report says about this tree: declared, required,
 *     emitted, switched off, and any gap
 *
 * Counts restated by hand drift — the posture document said "17 of 32" for a
 * day after the registry moved into configuration. The parity test already
 * pins the table's names to the map; this pins the whole region, so a tier
 * or description edit in configuration cannot leave the docs behind.
 *
 *   --check     Do not write; exit 1 if the generated output differs from
 *               disk. Used by `npm run docs:audit:check`, the pre-commit
 *               hook, and `npm run lint`.
 */

import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { coverage } from './audit-coverage';

const __filename = fileURLToPath(import.meta.url);
const REPO = path.resolve(path.dirname(__filename), '..');
const CHECK = process.argv.includes('--check');

const CONFIG = path.join(REPO, 'config', 'app-default-config.json');
const EVENTS_DOC = path.join(REPO, 'docs', 'managers', 'AuditManager.md');
const POSTURE_DOC = path.join(REPO, 'docs', 'audit-posture.md');

interface Declaration { tier: string; enabled?: boolean; description: string }

function declarations(): Record<string, Declaration> {
  const cfg = JSON.parse(readFileSync(CONFIG, 'utf8')) as Record<string, unknown>;
  return (cfg['ngdpbase.audit.events'] ?? {}) as Record<string, Declaration>;
}

/** The event table, as the manager document shows it. */
export function eventsTable(events: Record<string, Declaration> = declarations()): string {
  const rows = Object.entries(events).map(([name, d]) =>
    `| \`${name}\` | ${d.description} | ${d.tier} | ${d.enabled === false ? 'no' : 'yes'} |`
  );
  return ['| Event Type | Description | Tier | Recorded |', '| ----- | ----- | ----- | ----- |', ...rows].join('\n');
}

/** What the coverage report concludes, as the posture document shows it. */
export function coverageSection(events: Record<string, Declaration> = declarations()): string {
  const c = coverage();
  const off = Object.entries(events).filter(([, d]) => d.enabled === false).map(([n]) => n).sort();
  const critical = Object.entries(events).filter(([, d]) => d.tier === 'critical' && d.enabled !== false).map(([n]) => n).sort();
  const gaps = c.undeclared.length + c.unemitted.length + c.offVocabulary.length + c.unresolvedEmitters.length + c.offConvention.length;

  const lines = [
    '#### Results',
    '',
    'Generated by `npm run docs:audit` from `ngdpbase.audit.events` and `npm run audit:coverage`; `npm run docs:audit:check` fails the build when this section is stale.',
    '',
    '| | |',
    '| --- | --- |',
    `| Declared in configuration | ${c.vocabulary.length} |`,
    `| Required (declared and switched on) | ${c.registry.size} |`,
    `| Emitted by the source | ${c.emitted.length} |`,
    `| Switched off | ${off.length} |`,
    `| Critical tier | ${critical.length} |`,
    `| Gaps | ${gaps} |`,
    '',
    gaps === 0
      ? 'Every required event has an emitter, every emitted name is declared, and every name is `{target}-{action}`.'
      : `__${gaps} gap(s).__ Run \`npm run audit:coverage\` for the list; \`npm run lint:audit\` fails on each.`,
    '',
    `Switched off, on purpose, with the reason in each description: ${off.map((n) => `\`${n}\``).join(' · ')}.`,
    '',
    `Critical — the action does not complete unless the record does: ${critical.map((n) => `\`${n}\``).join(' · ')}.`
  ];
  return lines.join('\n');
}

function rewriteRegion(content: string, marker: string, body: string, file: string): string {
  const begin = `<!-- AUTO:${marker} BEGIN -->`;
  const end = `<!-- AUTO:${marker} END -->`;
  const i = content.indexOf(begin);
  const j = content.indexOf(end);
  if (i === -1 || j === -1 || j < i) throw new Error(`Marker pair "${marker}" not found in ${path.relative(REPO, file)}`);
  return content.slice(0, i + begin.length) + '\n' + body + '\n' + content.slice(j);
}

export function generate(): Array<{ file: string; content: string }> {
  const events = declarations();
  return [
    { file: EVENTS_DOC, content: rewriteRegion(readFileSync(EVENTS_DOC, 'utf8'), 'audit-events', eventsTable(events), EVENTS_DOC) },
    { file: POSTURE_DOC, content: rewriteRegion(readFileSync(POSTURE_DOC, 'utf8'), 'audit-coverage', coverageSection(events), POSTURE_DOC) }
  ];
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  let stale = 0;
  for (const { file, content } of generate()) {
    const onDisk = readFileSync(file, 'utf8');
    if (onDisk === content) continue;
    if (CHECK) {
      console.error(`${path.relative(REPO, file)} is stale — run \`npm run docs:audit\` and commit the result.`);
      stale += 1;
    } else {
      writeFileSync(file, content, 'utf8');
      console.log(`Regenerated ${path.relative(REPO, file)}`);
    }
  }
  if (CHECK) {
    if (stale > 0) process.exit(1);
    console.log('Audit docs match configuration (#1207).');
  }
  process.exit(0);
}
